#include "CheckPattern.h"
#include <stdarg.h> 

static CheckPattern* _instance;

void CheckPattern::createInstance() {
	_instance = new CheckPattern();
}

CheckPattern* CheckPattern::instance() {
	return _instance;
}

void CheckPattern::loadPattern() {
	vector<PatternElement*> elements;
	elements.push_back(new PatternElement(1, 1, 0, 2, 0));
	elements.push_back(new PatternElement(4, -1, 1, 1, 2));
	elements.push_back(new PatternElement(3, -1, 0, 1, 0));
	addPattern("1", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 0, 0));
	elements.push_back(new PatternElement(4, -1, 1, 0, 1));
	elements.push_back(new PatternElement(3, 1, 0, 1, 0));
	addPattern("2", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 1, 0));
	elements.push_back(new PatternElement(4, 1, -1, 0, 1));
	elements.push_back(new PatternElement(3, 1, 0, 0, 0));
	addPattern("3", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 2, 0));
	elements.push_back(new PatternElement(4, 0, 2, 2, 1));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	addPattern("4", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 2, 0));
	elements.push_back(new PatternElement(4, 2, 0, 2, 3));
	elements.push_back(new PatternElement(3, 0, 0, 3, 0));
	addPattern("5", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 0, 0));
	elements.push_back(new PatternElement(1, -1, 0, 0, 0));
	elements.push_back(new PatternElement(3, 0, 0, 2, 0));
	elements.push_back(new PatternElement(4, 1, 0, 0, 2));
	elements.push_back(new PatternElement(4, -1, 0, 0, 2));
	addPattern("S 6", true, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, -1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, -1, 0, -1, 1));
	addPattern("7", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 1, 0));
	elements.push_back(new PatternElement(3, 1, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, 1, 1, 3));
	addPattern("8", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 0, 0));
	elements.push_back(new PatternElement(1, 2, 0, 0, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, -2, 0, 0, 1));
	elements.push_back(new PatternElement(4, 2, 0, 0, 1));
	addPattern("S 9", true, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 2, 0));
	elements.push_back(new PatternElement(4, 2, 0, 1, 2));
	addPattern("11", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 1, 0));
	elements.push_back(new PatternElement(5, 1, -1, 1, 2));
	elements.push_back(new PatternElement(4, 1, 2, 1, -1));
	elements.push_back(new PatternElement(3, 2, 0, -1, 0));
	addPattern("12", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 1, 0));
	elements.push_back(new PatternElement(5, 1, -1, 1, 0));
	elements.push_back(new PatternElement(4, 1, 3, 1, 0));
	elements.push_back(new PatternElement(3, 3, 0, 0, 0));
	addPattern("13", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 1, 0));
	elements.push_back(new PatternElement(1, 2, 0, 0, 0));
	elements.push_back(new PatternElement(3, 1, 0, 2, 0));
	elements.push_back(new PatternElement(4, 2, 1, 0, 2));
	elements.push_back(new PatternElement(4, -1, 1, 1, 2));
	addPattern("14", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 0, 0));
	elements.push_back(new PatternElement(1, 1, 0, -1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, -2, 0, 0, 1));
	elements.push_back(new PatternElement(4, 1, 0, -1, 1));
	addPattern("15", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 1, 0));
	elements.push_back(new PatternElement(1, 1, 0, 0, 0));
	elements.push_back(new PatternElement(3, 0, 0, 2, 0));
	elements.push_back(new PatternElement(4, -2, 0, 1, 2));
	elements.push_back(new PatternElement(4, 1, 0, 0, 2));
	addPattern("16", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 4, 0));
	elements.push_back(new PatternElement(3, -2, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, -2, 4, 3));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	addPattern("17", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 4, 0));
	elements.push_back(new PatternElement(3, 1, 0, 3, 0));
	elements.push_back(new PatternElement(4, -1, 1, 4, 3));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	addPattern("18", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 2, 0));
	elements.push_back(new PatternElement(1, 1, 0, -1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, -2, 0, 2, 1));
	elements.push_back(new PatternElement(4, 1, 0, -1, 1));
	addPattern("19", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 3, 0));
	elements.push_back(new PatternElement(1, 1, 0, -1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, -1, 0, 3, 1));
	elements.push_back(new PatternElement(4, 1, 0, -1, 1));
	addPattern("20", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 0, 0));
	elements.push_back(new PatternElement(1, 2, 0, 2, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, -2, 0, 0, 1));
	elements.push_back(new PatternElement(4, 2, 0, 2, 1));
	addPattern("21", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 2, 0));
	elements.push_back(new PatternElement(1, 0, 0, 1, 0));
	elements.push_back(new PatternElement(5, -2, 0, 2, 1));
	elements.push_back(new PatternElement(3, 2, 0, 0, 0));
	elements.push_back(new PatternElement(4, 2, 0, 0, 1));
	addPattern("22", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 0, 0));
	elements.push_back(new PatternElement(1, 0, 0, 1, 0));
	elements.push_back(new PatternElement(5, -2, 0, 0, 1));
	elements.push_back(new PatternElement(3, 2, 0, 0, 0));
	elements.push_back(new PatternElement(4, 2, 0, 0, 1));
	addPattern("23", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 3, 0));
	elements.push_back(new PatternElement(4, -1, 1, 3, 2));
	elements.push_back(new PatternElement(3, 1, 0, 2, 0));
	addPattern("24", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, -1, 0));
	elements.push_back(new PatternElement(1, 0, 0, 1, 0));
	elements.push_back(new PatternElement(5, -1, 0, -1, 1));
	elements.push_back(new PatternElement(3, 2, 0, 0, 0));
	elements.push_back(new PatternElement(4, 2, 0, 0, 1));
	addPattern("25", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 1, 0));
	elements.push_back(new PatternElement(7, 0, 0, 0, 0));
	elements.push_back(new PatternElement(3, 1, 0, 0, 0));
	elements.push_back(new PatternElement(4, -2, 0, 1, 2));
	elements.push_back(new PatternElement(4, -2, -1, 1, -1));
	addPattern("26", false, false, elements);
	elements.push_back(new PatternElement(2, 3, 0, 1, 0));
	elements.push_back(new PatternElement(1, 2, 0, 0, 0));
	elements.push_back(new PatternElement(4, 2, 1, 0, 2));
	elements.push_back(new PatternElement(3, 1, 0, 2, 0));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 1, 3, 2, 1));
	addPattern("27", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 1, 0));
	elements.push_back(new PatternElement(5, -1, 1, 1, 2));
	elements.push_back(new PatternElement(5, 0, -2, 0, -1));
	elements.push_back(new PatternElement(3, -3, 0, 0, 0));
	elements.push_back(new PatternElement(4, -1, -3, 1, 0));
	addPattern("28", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 5, 0));
	elements.push_back(new PatternElement(3, -1, 0, 4, 0));
	elements.push_back(new PatternElement(4, 1, -1, 5, 4));
	addPattern("29", false, false, elements);
	elements.push_back(new PatternElement(2, 3, 0, 3, 0));
	elements.push_back(new PatternElement(3, 2, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 2, 3, 1, 3));
	addPattern("30", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 3, 0));
	elements.push_back(new PatternElement(5, 0, -2, 3, 2));
	elements.push_back(new PatternElement(4, 0, 2, 3, 2));
	elements.push_back(new PatternElement(3, 2, 0, 2, 0));
	addPattern("32", false, false, elements);
	elements.push_back(new PatternElement(2, 4, 0, 2, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 2, 4, 1, 2));
	addPattern("33", false, false, elements);
	elements.push_back(new PatternElement(2, 3, 0, 3, 0));
	elements.push_back(new PatternElement(1, 3, 0, 2, 0));
	elements.push_back(new PatternElement(3, 1, 0, 3, 0));
	elements.push_back(new PatternElement(4, 3, 1, 2, 3));
	addPattern("34", false, false, elements);
	elements.push_back(new PatternElement(2, 2, 0, 4, 0));
	elements.push_back(new PatternElement(3, 1, 0, 2, 0));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 2, 1, 4, 2));
	addPattern("35", false, false, elements);
	elements.push_back(new PatternElement(2, 4, 0, 2, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 4, 2, 2, 1));
	addPattern("36", false, false, elements);
	elements.push_back(new PatternElement(2, 3, 0, 3, 0));
	elements.push_back(new PatternElement(1, 1, 0, 4, 0));
	elements.push_back(new PatternElement(3, 4, 0, 3, 0));
	addPattern("37", false, false, elements);
	elements.push_back(new PatternElement(2, 3, 0, 3, 0));
	elements.push_back(new PatternElement(1, 0, 0, 4, 0));
	elements.push_back(new PatternElement(3, 2, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, 2, 4, 3));
	addPattern("38", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 3, 0));
	elements.push_back(new PatternElement(2, 0, 0, 4, 0));
	elements.push_back(new PatternElement(3, 1, 0, 5, 0));
	elements.push_back(new PatternElement(4, 1, 0, 5, 3));
	elements.push_back(new PatternElement(4, 1, -1, 5, 4));
	addPattern("39", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 1, 0));
	elements.push_back(new PatternElement(2, -1, 0, -3, 0));
	elements.push_back(new PatternElement(3, 0, 0, -1, 0));
	elements.push_back(new PatternElement(4, -1, 0, 1, -1));
	addPattern("40", false, false, elements);
	elements.push_back(new PatternElement(2, -1, 0, -3, 0));
	elements.push_back(new PatternElement(3, -1, 0, 0, 0));
	elements.push_back(new PatternElement(4, -1, 1, 0, -1));
	elements.push_back(new PatternElement(4, -1, 1, 0, 1));
	addPattern("41", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 2, 0));
	elements.push_back(new PatternElement(1, 2, 0, 1, 0));
	elements.push_back(new PatternElement(3, 1, 0, 3, 0));
	elements.push_back(new PatternElement(4, -1, 1, 2, 3));
	elements.push_back(new PatternElement(4, 2, 1, 1, 3));
	addPattern("42", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 2, 0));
	elements.push_back(new PatternElement(2, 0, 0, 4, 0));
	elements.push_back(new PatternElement(7, 0, 0, 4, 0));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, 0, 1, 4, 2));
	elements.push_back(new PatternElement(4, 0, -1, 4, 2));
	elements.push_back(new PatternElement(3, 1, 0, 4, 0));
	addPattern("43", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 1, 0));
	elements.push_back(new PatternElement(6, -2, 0, 1, 0));
	elements.push_back(new PatternElement(3, 1, 0, 2, 0));
	elements.push_back(new PatternElement(0, -1, 0, 3, 0));
	addPattern("ZANDOR1", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 2, 0));
	elements.push_back(new PatternElement(6, -2, 0, 2, 0));
	elements.push_back(new PatternElement(3, 1, 0, 2, 0));
	addPattern("ZANDOR2", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 2, 0));
	elements.push_back(new PatternElement(6, -1, 0, 2, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(0, 1, 0, 3, 0));
	addPattern("ZANDOR3", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 2, 0));
	elements.push_back(new PatternElement(4, 1, -1, 1, 2));
	elements.push_back(new PatternElement(3, 1, 0, 1, 0));
	addPattern("1 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 0, 0));
	elements.push_back(new PatternElement(4, 1, -1, 0, 1));
	elements.push_back(new PatternElement(3, -1, 0, 1, 0));
	addPattern("2 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 1, 0));
	elements.push_back(new PatternElement(4, -1, 1, 0, 1));
	elements.push_back(new PatternElement(3, -1, 0, 0, 0));
	addPattern("3 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 2, 0));
	elements.push_back(new PatternElement(4, 0, -2, 2, 1));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	addPattern("4 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 2, 0));
	elements.push_back(new PatternElement(4, -2, 0, 2, 3));
	elements.push_back(new PatternElement(3, 0, 0, 3, 0));
	addPattern("5 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, -1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, 1, 0, -1, 1));
	addPattern("7 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 1, 0));
	elements.push_back(new PatternElement(3, -1, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, -1, 1, 3));
	addPattern("8 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, -2, 0, 1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 2, 0));
	elements.push_back(new PatternElement(4, -2, 0, 1, 2));
	addPattern("11 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 1, 0));
	elements.push_back(new PatternElement(5, -1, 1, 1, 2));
	elements.push_back(new PatternElement(4, -1, -2, 1, -1));
	elements.push_back(new PatternElement(3, -2, 0, -1, 0));
	addPattern("12 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 1, 0));
	elements.push_back(new PatternElement(5, -1, 1, 1, 0));
	elements.push_back(new PatternElement(4, -1, -3, 1, 0));
	elements.push_back(new PatternElement(3, -3, 0, 0, 0));
	addPattern("13 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 1, 0));
	elements.push_back(new PatternElement(1, -2, 0, 0, 0));
	elements.push_back(new PatternElement(3, -1, 0, 2, 0));
	elements.push_back(new PatternElement(4, -2, -1, 0, 2));
	elements.push_back(new PatternElement(4, 1, -1, 1, 2));
	addPattern("14 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 0, 0));
	elements.push_back(new PatternElement(1, -1, 0, -1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, 2, 0, 0, 1));
	elements.push_back(new PatternElement(4, -1, 0, -1, 1));
	addPattern("15 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 1, 0));
	elements.push_back(new PatternElement(1, -1, 0, 0, 0));
	elements.push_back(new PatternElement(3, 0, 0, 2, 0));
	elements.push_back(new PatternElement(4, 2, 0, 1, 2));
	elements.push_back(new PatternElement(4, -1, 0, 0, 2));
	addPattern("16 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 4, 0));
	elements.push_back(new PatternElement(3, 2, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, 2, 4, 3));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	addPattern("17 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 4, 0));
	elements.push_back(new PatternElement(3, -1, 0, 3, 0));
	elements.push_back(new PatternElement(4, 1, -1, 4, 3));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	addPattern("18 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 2, 0));
	elements.push_back(new PatternElement(1, -1, 0, -1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, 2, 0, 2, 1));
	elements.push_back(new PatternElement(4, -1, 0, -1, 1));
	addPattern("19 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 3, 0));
	elements.push_back(new PatternElement(1, -1, 0, -1, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, 1, 0, 3, 1));
	elements.push_back(new PatternElement(4, -1, 0, -1, 1));
	addPattern("20 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 0, 0));
	elements.push_back(new PatternElement(1, -2, 0, 2, 0));
	elements.push_back(new PatternElement(3, 0, 0, 1, 0));
	elements.push_back(new PatternElement(4, 2, 0, 0, 1));
	elements.push_back(new PatternElement(4, -2, 0, 2, 1));
	addPattern("21 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 2, 0));
	elements.push_back(new PatternElement(1, 0, 0, 1, 0));
	elements.push_back(new PatternElement(5, 2, 0, 2, 1));
	elements.push_back(new PatternElement(3, -2, 0, 0, 0));
	elements.push_back(new PatternElement(4, -2, 0, 0, 1));
	addPattern("22 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 0, 0));
	elements.push_back(new PatternElement(1, 0, 0, 1, 0));
	elements.push_back(new PatternElement(5, 2, 0, 0, 1));
	elements.push_back(new PatternElement(3, -2, 0, 0, 0));
	elements.push_back(new PatternElement(4, -2, 0, 0, 1));
	addPattern("23 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 3, 0));
	elements.push_back(new PatternElement(4, 1, -1, 3, 2));
	elements.push_back(new PatternElement(3, -1, 0, 2, 0));
	addPattern("24 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, -1, 0));
	elements.push_back(new PatternElement(1, 0, 0, 1, 0));
	elements.push_back(new PatternElement(5, 1, 0, -1, 1));
	elements.push_back(new PatternElement(3, -2, 0, 0, 0));
	elements.push_back(new PatternElement(4, -2, 0, 0, 1));
	addPattern("25 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 1, 0));
	elements.push_back(new PatternElement(7, 0, 0, 0, 0));
	elements.push_back(new PatternElement(3, -1, 0, 0, 0));
	elements.push_back(new PatternElement(4, 2, 0, 1, 2));
	elements.push_back(new PatternElement(4, 2, 1, 1, -1));
	addPattern("26 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, -3, 0, 1, 0));
	elements.push_back(new PatternElement(1, -2, 0, 0, 0));
	elements.push_back(new PatternElement(4, -2, -1, 0, 2));
	elements.push_back(new PatternElement(3, -1, 0, 2, 0));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, -1, -3, 2, 1));
	addPattern("27 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 1, 0));
	elements.push_back(new PatternElement(5, 1, -1, 1, 2));
	elements.push_back(new PatternElement(5, 0, 2, 0, -1));
	elements.push_back(new PatternElement(3, 3, 0, 0, 0));
	elements.push_back(new PatternElement(4, 1, 3, 1, 0));
	addPattern("28 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, -1, 0, 5, 0));
	elements.push_back(new PatternElement(3, 1, 0, 4, 0));
	elements.push_back(new PatternElement(4, -1, 1, 5, 4));
	addPattern("29 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, -3, 0, 3, 0));
	elements.push_back(new PatternElement(3, -2, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -2, -3, 1, 3));
	addPattern("30 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 3, 0));
	elements.push_back(new PatternElement(5, 0, 2, 3, 2));
	elements.push_back(new PatternElement(4, 0, -2, 3, 2));
	elements.push_back(new PatternElement(3, -2, 0, 2, 0));
	addPattern("32 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, -4, 0, 2, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, -2, -4, 1, 2));
	addPattern("33 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, -3, 0, 3, 0));
	elements.push_back(new PatternElement(1, -3, 0, 2, 0));
	elements.push_back(new PatternElement(3, -1, 0, 3, 0));
	elements.push_back(new PatternElement(4, -3, -1, 2, 3));
	addPattern("34 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, -2, 0, 4, 0));
	elements.push_back(new PatternElement(3, -1, 0, 2, 0));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, -2, -1, 4, 2));
	addPattern("35 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, -4, 0, 2, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -4, -2, 2, 1));
	addPattern("36 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, -3, 0, 3, 0));
	elements.push_back(new PatternElement(1, -1, 0, 4, 0));
	elements.push_back(new PatternElement(3, -4, 0, 3, 0));
	addPattern("37 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, -3, 0, 3, 0));
	elements.push_back(new PatternElement(1, 0, 0, 4, 0));
	elements.push_back(new PatternElement(3, -2, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, -2, 4, 3));
	addPattern("38 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 3, 0));
	elements.push_back(new PatternElement(2, 0, 0, 4, 0));
	elements.push_back(new PatternElement(3, -1, 0, 5, 0));
	elements.push_back(new PatternElement(4, -1, 0, 5, 3));
	elements.push_back(new PatternElement(4, -1, 1, 5, 4));
	addPattern("39 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 1, 0));
	elements.push_back(new PatternElement(2, 1, 0, -3, 0));
	elements.push_back(new PatternElement(3, 0, 0, -1, 0));
	elements.push_back(new PatternElement(4, 1, 0, 1, -1));
	addPattern("40 mirrored", false, false, elements);
	elements.push_back(new PatternElement(2, 1, 0, -3, 0));
	elements.push_back(new PatternElement(3, 1, 0, 0, 0));
	elements.push_back(new PatternElement(4, 1, -1, 0, -1));
	elements.push_back(new PatternElement(4, 1, -1, 0, 1));
	addPattern("41 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 2, 0));
	elements.push_back(new PatternElement(1, -2, 0, 1, 0));
	elements.push_back(new PatternElement(3, -1, 0, 3, 0));
	elements.push_back(new PatternElement(4, 1, -1, 2, 3));
	elements.push_back(new PatternElement(4, -2, -1, 1, 3));
	addPattern("42 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 0, 0, 2, 0));
	elements.push_back(new PatternElement(2, 0, 0, 4, 0));
	elements.push_back(new PatternElement(7, 0, 0, 4, 0));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 0, -1, 4, 2));
	elements.push_back(new PatternElement(4, 0, 1, 4, 2));
	elements.push_back(new PatternElement(3, -1, 0, 4, 0));
	addPattern("43 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 1, 0));
	elements.push_back(new PatternElement(6, 2, 0, 1, 0));
	elements.push_back(new PatternElement(3, -1, 0, 2, 0));
	elements.push_back(new PatternElement(0, 1, 0, 3, 0));
	addPattern("ZANDOR1 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 2, 0, 2, 0));
	elements.push_back(new PatternElement(6, 2, 0, 2, 0));
	elements.push_back(new PatternElement(3, -1, 0, 2, 0));
	addPattern("ZANDOR2 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 1, 0, 2, 0));
	elements.push_back(new PatternElement(6, 1, 0, 2, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(0, -1, 0, 3, 0));
	addPattern("ZANDOR3 mirrored", false, false, elements);
	elements.push_back(new PatternElement(1, 4, 0, 2, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 4, 2, 2, 1));
	addPattern("1", false, true, elements);
	elements.push_back(new PatternElement(1, 3, 0, 3, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 3, 2, 3, 1));
	addPattern("2", false, true, elements);
	elements.push_back(new PatternElement(1, 1, 0, 3, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 1, 2, 3, 1));
	addPattern("3", false, true, elements);
	elements.push_back(new PatternElement(1, 3, 0, 1, 0));
	elements.push_back(new PatternElement(3, 2, 0, -1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, -1));
	elements.push_back(new PatternElement(4, 3, 2, 1, -1));
	addPattern("4", false, true, elements);
	elements.push_back(new PatternElement(1, 0, 0, 2, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 2, 0, 1, 2));
	addPattern("5", false, true, elements);
	elements.push_back(new PatternElement(1, 4, 0, 0, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 2, 4, 1, 0));
	addPattern("6", false, true, elements);
	elements.push_back(new PatternElement(1, 4, 0, 0, 0));
	elements.push_back(new PatternElement(3, 2, 0, -1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, -1));
	elements.push_back(new PatternElement(4, 2, 4, -1, 0));
	addPattern("7", false, true, elements);
	elements.push_back(new PatternElement(1, 1, 0, 1, 0));
	elements.push_back(new PatternElement(3, 2, 0, -1, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, -1));
	elements.push_back(new PatternElement(4, 1, 2, 1, -1));
	addPattern("8", false, true, elements);
	elements.push_back(new PatternElement(1, 2, 0, 1, 0));
	elements.push_back(new PatternElement(1, 5, 0, 2, 0));
	elements.push_back(new PatternElement(5, 0, 2, 0, 1));
	elements.push_back(new PatternElement(3, 4, 0, 0, 0));
	elements.push_back(new PatternElement(4, 2, 4, 1, 0));
	elements.push_back(new PatternElement(4, 5, 4, 2, 0));
	addPattern("9", false, true, elements);
	elements.push_back(new PatternElement(1, 3, 0, -1, 0));
	elements.push_back(new PatternElement(3, 2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 2, 3, 1, -1));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	addPattern("10", false, true, elements);
	elements.push_back(new PatternElement(2, -1, 0, 2, 0));
	elements.push_back(new PatternElement(3, -1, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -2, -1, 1, 3));
	elements.push_back(new PatternElement(4, 1, -1, 2, 3));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	addPattern("11", false, true, elements);
	elements.push_back(new PatternElement(5, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -2, -3, 1, 3));
	elements.push_back(new PatternElement(3, -3, 0, 3, 0));
	addPattern("12", false, true, elements);
	elements.push_back(new PatternElement(1, 2, 0, 0, 0));
	elements.push_back(new PatternElement(3, 1, 0, -2, 0));
	elements.push_back(new PatternElement(4, 0, 1, 0, -2));
	elements.push_back(new PatternElement(4, 1, 2, -2, 0));
	addPattern("13", false, true, elements);
	elements.push_back(new PatternElement(2, 0, 0, 2, 0));
	elements.push_back(new PatternElement(3, 0, 0, 4, 0));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, 0, -1, 4, 2));
	elements.push_back(new PatternElement(4, 0, 1, 4, 2));
	addPattern("S UEBERSPRINGEN", true, true, elements);
	elements.push_back(new PatternElement(0, 1, 0, 2, 0));
	elements.push_back(new PatternElement(0, -1, 0, 2, 0));
	elements.push_back(new PatternElement(6, 0, 0, 0, 0));
	elements.push_back(new PatternElement(3, 0, 0, 4, 0));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, 0, 1, 4, 2));
	elements.push_back(new PatternElement(4, 0, -1, 4, 2));
	addPattern("S A", true, true, elements);
	elements.push_back(new PatternElement(0, -2, 0, 1, 0));
	elements.push_back(new PatternElement(0, -1, 0, 2, 0));
	elements.push_back(new PatternElement(3, -3, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	elements.push_back(new PatternElement(4, -3, -2, 3, 1));
	elements.push_back(new PatternElement(4, -3, -1, 3, 2));
	addPattern("B", false, true, elements);
	elements.push_back(new PatternElement(1, -4, 0, 2, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -4, -2, 2, 1));
	addPattern("1 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -3, 0, 3, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -3, -2, 3, 1));
	addPattern("2 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -1, 0, 3, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -1, -2, 3, 1));
	addPattern("3 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -3, 0, 1, 0));
	elements.push_back(new PatternElement(3, -2, 0, -1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, -1));
	elements.push_back(new PatternElement(4, -3, -2, 1, -1));
	addPattern("4 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, 0, 0, 2, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -2, 0, 1, 2));
	addPattern("5 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -4, 0, 0, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	elements.push_back(new PatternElement(4, -2, -4, 1, 0));
	addPattern("6 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -4, 0, 0, 0));
	elements.push_back(new PatternElement(3, -2, 0, -1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, -1));
	elements.push_back(new PatternElement(4, -2, -4, -1, 0));
	addPattern("7 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -1, 0, 1, 0));
	elements.push_back(new PatternElement(3, -2, 0, -1, 0));
	elements.push_back(new PatternElement(4, 0, -2, 0, -1));
	elements.push_back(new PatternElement(4, -1, -2, 1, -1));
	addPattern("8 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -2, 0, 1, 0));
	elements.push_back(new PatternElement(1, -5, 0, 2, 0));
	elements.push_back(new PatternElement(5, 0, -2, 0, 1));
	elements.push_back(new PatternElement(3, -4, 0, 0, 0));
	elements.push_back(new PatternElement(4, -2, -4, 1, 0));
	elements.push_back(new PatternElement(4, -5, -4, 2, 0));
	addPattern("9 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -3, 0, -1, 0));
	elements.push_back(new PatternElement(3, -2, 0, 1, 0));
	elements.push_back(new PatternElement(4, -2, -3, 1, -1));
	elements.push_back(new PatternElement(4, 0, -2, 0, 1));
	addPattern("10 mirrored", false, true, elements);
	elements.push_back(new PatternElement(2, 1, 0, 2, 0));
	elements.push_back(new PatternElement(3, 1, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 2, 1, 1, 3));
	elements.push_back(new PatternElement(4, -1, 1, 2, 3));
	elements.push_back(new PatternElement(4, 0, -1, 0, 2));
	addPattern("11 mirrored", false, true, elements);
	elements.push_back(new PatternElement(5, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 2, 3, 1, 3));
	elements.push_back(new PatternElement(3, 3, 0, 3, 0));
	addPattern("12 mirrored", false, true, elements);
	elements.push_back(new PatternElement(1, -2, 0, 0, 0));
	elements.push_back(new PatternElement(3, -1, 0, -2, 0));
	elements.push_back(new PatternElement(4, 0, -1, 0, -2));
	elements.push_back(new PatternElement(4, -1, -2, -2, 0));
	addPattern("13 mirrored", false, true, elements);
	elements.push_back(new PatternElement(0, 2, 0, 1, 0));
	elements.push_back(new PatternElement(0, 1, 0, 2, 0));
	elements.push_back(new PatternElement(3, 3, 0, 3, 0));
	elements.push_back(new PatternElement(4, 0, 2, 0, 1));
	elements.push_back(new PatternElement(4, 0, 1, 0, 2));
	elements.push_back(new PatternElement(4, 3, 2, 3, 1));
	elements.push_back(new PatternElement(4, 3, 1, 3, 2));
	addPattern("B mirrored", false, true, elements);
}

void CheckPattern::addPattern(string name, bool b, bool offensive, vector<PatternElement*>& elements) {
	Pattern* p = new Pattern(name, b);
	for(PatternElement* pe : elements)
		p->addElement(pe);
	if (offensive)
		offensivePatterns.push_back(p);
	else
		defensivePatterns.push_back(p);
	elements.clear();
}

void CheckPattern::findPatternMoves(unordered_set<Move, Move::Hash>& mvs, bool offense, Board* board, CritPos& critPos, int player) {
	moves = &mvs;
	for (Pattern* e : (offense ? offensivePatterns : defensivePatterns))
		e->checkPatternElements(&critPos, board, player, offense);
}
